spring:
  application:
    name: MS_Gateway
  cloud: 
   gateway:
     default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
     globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
     routes:
      - id: MS_Alumnos 
        uri: lb://curso-springboot-cta
        predicates:
          - Path=/api/students/**
        filters:
          - RewritePath=/api/students/*, /students/
server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka